#!/usr/bin/env escript

main([TabFile]) ->
	tab_file(TabFile, []);
main(["-f",TabFile]) ->
	tab_file(TabFile, [raw]).

tab_file(TabFile, Opts) ->
	ScriptDir = filename:dirname(escript:script_name()),
	EbinDir = filename:join([ScriptDir,"..","ebin"]),
	code:add_pathz(EbinDir),

	{ok,FlowEnts} = file:consult(TabFile),
	BaseName = filename:basename(TabFile, ".tab"),
	TabName = list_to_atom(BaseName),

	{ok,Forms} = linc_max_generator:flow_table_forms(TabName, FlowEnts),

	case lists:member(raw, Opts) of
	true ->
		io:format("~p\n", [Forms]);
	false ->
		lists:foreach(fun(Form) ->
			io:format("~s", [erl_pp:form(Form)])
		end, Forms)
	end.

%%EOF
