%% Autogenerated by ./scripts/fast_actions_gen

apply_set({_,undefined,undefined,undefined,undefined},Frame,_Blaze) ->
	Frame;
apply_set({_,undefined,undefined,undefined,PortNo},Frame,_Blaze) ->
	output(Frame,PortNo,_Blaze);
apply_set({_,undefined,undefined,Group,undefined},Frame,_Blaze) ->
	group(Frame,Group);
apply_set({_,undefined,undefined,Group,PortNo},Frame,_Blaze) ->
	output(group(Frame,Group),PortNo,_Blaze);
apply_set({_,undefined,Queue,undefined,undefined},Frame,_Blaze) ->
	set_queue(Frame,Queue,_Blaze);
apply_set({_,undefined,Queue,undefined,PortNo},Frame,_Blaze) ->
	output(set_queue(Frame,Queue,_Blaze),PortNo,_Blaze);
apply_set({_,undefined,Queue,Group,undefined},Frame,_Blaze) ->
	group(set_queue(Frame,Queue,_Blaze),Group);
apply_set({_,undefined,Queue,Group,PortNo},Frame,_Blaze) ->
	output(group(set_queue(Frame,Queue,_Blaze),Group),PortNo,_Blaze);
apply_set({_,Set1,undefined,undefined,undefined},Frame,_Blaze) ->
	apply_subset(Frame,Set1);
apply_set({_,Set1,undefined,undefined,PortNo},Frame,_Blaze) ->
	output(apply_subset(Frame,Set1),PortNo,_Blaze);
apply_set({_,Set1,undefined,Group,undefined},Frame,_Blaze) ->
	group(apply_subset(Frame,Set1),Group);
apply_set({_,Set1,undefined,Group,PortNo},Frame,_Blaze) ->
	output(group(apply_subset(Frame,Set1),Group),PortNo,_Blaze);
apply_set({_,Set1,Queue,undefined,undefined},Frame,_Blaze) ->
	set_queue(apply_subset(Frame,Set1),Queue,_Blaze);
apply_set({_,Set1,Queue,undefined,PortNo},Frame,_Blaze) ->
	output(set_queue(apply_subset(Frame,Set1),Queue,_Blaze),PortNo,_Blaze);
apply_set({_,Set1,Queue,Group,undefined},Frame,_Blaze) ->
	group(set_queue(apply_subset(Frame,Set1),Queue,_Blaze),Group);
apply_set({_,Set1,Queue,Group,PortNo},Frame,_Blaze) ->
	output(group(set_queue(apply_subset(Frame,Set1),Queue,_Blaze),Group),PortNo,_Blaze).

